use_frameworks!

platform :ios, '8.0'

target 'Ou_CutVideo_Example' do
  pod 'Ou_CutVideo', :path => '../'

  target 'Ou_CutVideo_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
